/*
-- Query: SELECT * FROM herpetology.classifications
LIMIT 0, 1000

-- Date: 2021-03-11 16:16
*/
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (1,'aestivus',2,5,22);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (2,'alleganiensis',1,6,10);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (3,'allegheniensis',2,5,35);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (4,'americanus',1,3,7);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (5,'anthracinus',2,15,17);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (6,'bislineata',1,12,15);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (7,'carolina',2,7,26);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (8,'catesbiana',1,10,2);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (9,'cinereus',1,12,1);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (10,'clamitans',1,10,2);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (11,'constrictor',2,5,18);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (12,'contortrix',2,17,39);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (13,'crepitans',1,8,9);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (14,'crucifer',1,8,3);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (15,'dekayi',2,5,23);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (16,'fasciatus',2,15,38);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (17,'ferarium',1,8,3);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (18,'fowleri',1,3,7);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (19,'fuscus',1,12,6);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (20,'geographica',2,7,28);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (21,'getulus',2,5,19);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (22,'glutinosus',1,12,1);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (23,'guttata',2,7,16);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (24,'holbrookii',1,14,13);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (25,'horridus',2,17,37);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (26,'insculpta',2,7,16);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (27,'jeffersonium',1,1,4);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (28,'laticeps',2,15,17);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (29,'longicauda',1,12,15);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (30,'maculatum',1,1,4);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (31,'muhlenbergii',2,7,16);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (32,'nettingi',1,12,1);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (33,'ochrophaeus',1,12,6);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (34,'odoratus',2,9,32);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (35,'opacum',1,1,4);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (36,'palustris',1,10,2);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (37,'picta',2,7,27);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (38,'platyrhinos',2,9,41);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (39,'porphyriticus',1,12,11);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (40,'punctatus',2,5,40);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (41,'ruber',1,12,14);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (42,'rubiventris',2,7,29);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (43,'sauritus',2,5,21);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (44,'scipta',2,7,30);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (45,'scutatum',1,12,12);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (46,'semptemvittata',2,5,20);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (47,'serpentina',2,4,25);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (48,'sipedon',2,5,36);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (49,'sirtalis',2,5,21);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (50,'sphenocephalus',1,10,2);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (51,'spiniferus',2,16,33);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (52,'subrubrum',2,9,31);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (53,'sylvatica',1,10,2);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (54,'triangulum',2,5,19);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (55,'undulatus',2,11,34);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (56,'valeriae',2,5,24);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (57,'vernalis',2,5,22);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (58,'versicolor',1,8,8);
INSERT INTO `` (`classification_id`,`species`,`class_id`,`family_id`,`genus_id`) VALUES (59,'viridescens',1,13,5);
